### ISSUE TITLE
Fails to retrieve artifact from localRepository when using win path.

### ISSUE THREAD

**Issue by yoshiya8** [lucastheisen/perl-maven#2]
My `settings.xml` file specifies the location of the Maven `localRepository` as a Windows path:
```xml
<localRepository>D:\M2\repository</localRepository>
````
When I try to use `perl-maven` to retrieve a SNAPSHOT artifact from my `localRepository`, I get the following output:
```
loading snapshot metadata from ./D:M2repository/group/artifact/version-SNAPSHOT
```
and eventually fails, saying:
```
artifact group:artifact:war:version-SNAPSHOT not found at /usr/lib/perl5/site_perl/5.22/Maven/Agent.pm line 90.
```
If I change my `settings.xml` file to specify the location of the Maven `localRepository` as with Java pseudo-windows path as follows, it works perfectly fine:
```xml
<localRepository>D:/M2/repository</localRepository>
````
Clearly the backslashes in the `localRepository` value are being removed and it's being treated as a relative instead of absolute path.

Evidently the `_init` subroutine in `lib\Maven\LocalRepository.pm` file the backslashes in the `local_repository_path` get devoured somewhere in the shelling out of the `cygpath` call:
```perl
sub _init {
    my ($self, $local_repository_path, @args) = @_;

    $self->Maven::Repository::_init( 
        URI::file->new($^O =~ /^cygwin$/i
            #? Cygwin::win_to_posix_path($local_repository_path)
            ? `cygpath -u $local_repository_path`
            : $local_repository_path)->as_string());

    return $self;
}
```

**Comment by lucastheisen** [comment]
Thank you, resolved and released as version 1.14...  Should be available in the next hour or two.
